#!/bin/bash

TRUE=1
FALSE=0

home_directory=$PWD
ig_builder_output_path="${home_directory}/output"

ig_generated_package_name="package.r4.tgz"
output_directory="${home_directory}/package"

echo "ig builder output path: ${ig_builder_output_path}"
echo "Package output directory: ${output_directory}"

PrepareOutputDirectory ()
{
  local ERROR=$FALSE
  echo "Recreating package output location"

  if [[ -d "${output_directory}" ]]
  then
    removed=`rm -f -v -r "${output_directory}" 2>&1` || ERROR=$TRUE
    if [[ ${ERROR} -eq ${TRUE} ]]; then
      echo "ERROR: Cannot remove files in output directory"
      echo -e "---------------------------\n${removed}\n------------------------------"
      exit 1
    fi
  fi
  created=`mkdir -p "${output_directory}" 2>&1`|| ERROR=$TRUE
  if [[ ${ERROR} -eq ${TRUE} ]]; then
    echo "ERROR: output directory '${output_directory}' could not be recreated"
    echo -e "--------------------------- \n${created}\n---------------------------------"
    exit 1
  fi
}

RemoveUnwantedFiles()
{
  echo "Removing unwanted files"
  local FILES=`find ${output_directory}/package -mindepth 1 -maxdepth 1 -type f \( -iname 'Parameters-*' -o -iname 'ImplementationGuide-*' -o \! -iname '[!.]*.json' \)`
  for file in ${FILES[@]}
  do
    echo "removing:" $file
    succes=`rm $file 2>&1` || ERROR=$TRUE
    if [[ ${ERROR} -eq ${TRUE} ]]; then
      echo "ERROR: Unable to remove unwanted files, exiting"
      echo -e "--------------------------- \n${succes}\n---------------------------------"
      exit 1
    fi
  done
}

RemoveUnwantedDirs()
{
  echo "Removing unwanted directories"
  local DIRS=`find ${output_directory}/package -mindepth 1 -maxdepth 1 -type d -not -iname example`
  for dir in ${DIRS[@]}
  do
    echo "removing:" $dir
    succes=`rm -r $dir 2>&1` || ERROR=$TRUE
    if [[ ${ERROR} -eq ${TRUE} ]]; then
      echo "ERROR: Unable to remove unwanted directories, exiting"
      echo -e "--------------------------- \n${succes}\n---------------------------------"
      exit 1
    fi
  done
}

UnpackTarFile()
{
  local ERROR=$FALSE

  local source_package_file="${ig_builder_output_path}/${ig_generated_package_name}"
  echo "package file name: ${source_package_file}"
  [[ ! -f "${source_package_file}" ]] && echo "Package file '${ig_generated_package_name}' not found in IG output folder" && exit 1

  local result=`tar -xvzf "${source_package_file}" -C "${output_directory}" 2>&1` || ERROR=$TRUE
  if [[ $ERROR -eq $TRUE ]]; then
    echo "Unable to extract package generated by IG builder."
    exit 1
  fi
}

CreateTarFile()
{
  local ERROR=$FALSE

  local tar_filename="${PACKAGE_NAME}.tgz"
  echo "Compressing profile files to package ${tar_filename}"

  echo "Package directory: ${output_directory}"
  cd "${output_directory}"

  result=`tar -cvzf "${tar_filename}" "package" 2>&1` || ERROR=$TRUE
  if [[ ${ERROR} -eq ${TRUE} ]]
  then
    echo "ERROR: Unable to compress files."
    echo -e "--------------------------- \n${result}\n---------------------------------"
    exit 1
  fi
  echo "files were compressed at ${output_directory} to '${tar_filename}'"
}

UpdatePackageFile()
{
  echo "Updating package.json"
  local ERROR=$FALSE

  local package_filename="${output_directory}/package/package.json"
  cat "${package_filename}" | jq 'del(.canonical)' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(.title)' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(.type)' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(.url)' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(."tools-version")' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(."date")' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(.license)' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(."notForPublication")' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(.dependencies."hl7.terminology.r4")' | tee "${package_filename}"  >/dev/null
  cat "${package_filename}" | jq 'del(.dependencies."hl7.fhir.uv.extensions.r4")' | tee "${package_filename}"  >/dev/null
  cat "${package_filename}" | jq  '.name="iknl.fhir.nl.r4.ncr-ehr"' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq '. += {jurisdiction : "urn:iso:std:iso:3166#NL"}' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq  '.description="FHIR R4 profiles for the electronic health record (EHR) submissions to the Netherlands Cancer Registry (NCR)"' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(."directories")' | tee "${package_filename}" >/dev/null
  cat "${package_filename}" | jq 'del(."maintainers")' | tee "${package_filename}" >/dev/null
}

for arg in "$@";
do
  name="${arg/=*/}"
  value="${arg/${name}=/}"
  case "${name}" in
    --package-name)
      [[ "${value}" == "${name}" ]] && echo "No package name provided"
      PACKAGE_NAME="${value}"
      ;;
 esac
done

[[ "${PACKAGE_NAME}" == "" ]] && echo "No package name was provided, use '--package-name' as an argument to specify a package name" && exit 1
[[ ! -d "${ig_builder_output_path}" ]] && echo "IG output path ${ig_builder_output_path} does not exist" && exit 1
[[ ! $(ls -A ${ig_builder_output_path}) ]] && echo "IG Output directory is empty" && exit 1

PrepareOutputDirectory
UnpackTarFile
RemoveUnwantedFiles
RemoveUnwantedDirs
UpdatePackageFile
CreateTarFile

echo "Done."