#!/bin/bash

TRUE=1
FALSE=0

home_directory="${HOME_DIRECTORY:-$PWD}"
ig_builder_output_path="${IG_BUILDER_OUTPUT_PATH:-${home_directory}/output}"
final_output_directory="${FINAL_OUTPUT_DIR:-}"

ig_generated_package_name="package.r4.tgz"
output_directory="${home_directory}/package"

echo "ig builder output path: ${ig_builder_output_path}"
echo "Package output directory: ${output_directory}"

PrepareOutputDirectory ()
{
  local ERROR=$FALSE
  echo "Recreating package output location"

  if [[ -d "${output_directory}" ]]
  then
    removed=`rm -f -v -r "${output_directory}" 2>&1` || ERROR=$TRUE
    if [[ ${ERROR} -eq ${TRUE} ]]; then
      echo "ERROR: Cannot remove files in output directory"
      echo -e "---------------------------\n${removed}\n------------------------------"
      exit 1
    fi
  fi
  created=`mkdir -p "${output_directory}" 2>&1`|| ERROR=$TRUE
  if [[ ${ERROR} -eq ${TRUE} ]]; then
    echo "ERROR: output directory '${output_directory}' could not be recreated"
    echo -e "--------------------------- \n${created}\n---------------------------------"
    exit 1
  fi
}

RemoveUnwantedFiles()
{
  echo "Removing unwanted files"
  local ERROR=$FALSE
  local FILES=`find ${output_directory}/package -mindepth 1 -maxdepth 1 -type f \( -iname 'Parameters-*' -o -iname 'ImplementationGuide-*' -o \! -iname '[!.]*.json' \)`
  for file in ${FILES[@]}
  do
    echo "removing:" $file
    succes=`rm $file 2>&1` || ERROR=$TRUE
    if [[ ${ERROR} -eq ${TRUE} ]]; then
      echo "ERROR: Unable to remove unwanted files, exiting"
      echo -e "--------------------------- \n${succes}\n---------------------------------"
      exit 1
    fi
  done
}

RemoveUnwantedDirs()
{
  echo "Removing unwanted directories"
  local ERROR=$FALSE
  local DIRS=`find ${output_directory}/package -mindepth 1 -maxdepth 1 -type d -not -iname example`
  for dir in ${DIRS[@]}
  do
    echo "removing:" $dir
    succes=`rm -r $dir 2>&1` || ERROR=$TRUE
    if [[ ${ERROR} -eq ${TRUE} ]]; then
      echo "ERROR: Unable to remove unwanted directories, exiting"
      echo -e "--------------------------- \n${succes}\n---------------------------------"
      exit 1
    fi
  done
}

UnpackTarFile()
{
  local ERROR=$FALSE

  local source_package_file="${ig_builder_output_path}/${ig_generated_package_name}"
  echo "package file name: ${source_package_file}"
  [[ ! -f "${source_package_file}" ]] && echo "Package file '${ig_generated_package_name}' not found in IG output folder" && exit 1

  local result=`tar -xvzf "${source_package_file}" -C "${output_directory}" 2>&1` || ERROR=$TRUE
  if [[ $ERROR -eq $TRUE ]]; then
    echo "Unable to extract package generated by IG builder."
    exit 1
  fi
}

CreateTarFile()
{
  local ERROR=$FALSE

  local tar_filename="${PACKAGE_NAME}.tgz"
  echo "Compressing profile files to package ${tar_filename}"

  echo "Package directory: ${output_directory}"
  cd "${output_directory}"

  result=`tar -cvzf "${tar_filename}" "package" 2>&1` || ERROR=$TRUE
  if [[ ${ERROR} -eq ${TRUE} ]]
  then
    echo "ERROR: Unable to compress files."
    echo -e "--------------------------- \n${result}\n---------------------------------"
    exit 1
  fi
  echo "files were compressed at ${output_directory} to '${tar_filename}'"
}

CopyToFinalOutput()
{
  if [[ -z "${final_output_directory}" ]]; then
    return 0
  fi

  local ERROR=$FALSE
  local source_tar="${output_directory}/${PACKAGE_NAME}.tgz"
  local output_filename="${OUTPUT_FILENAME:-${PACKAGE_NAME}.tgz}"
  local destination="${final_output_directory}/${output_filename}"

  echo "Copying package to ${destination}"
  created=`mkdir -p "${final_output_directory}" 2>&1` || ERROR=$TRUE
  if [[ ${ERROR} -eq ${TRUE} ]]; then
    echo "ERROR: output directory '${final_output_directory}' could not be created"
    echo -e "--------------------------- \n${created}\n---------------------------------"
    exit 1
  fi

  copied=`cp "${source_tar}" "${destination}" 2>&1` || ERROR=$TRUE
  if [[ ${ERROR} -eq ${TRUE} ]]; then
    echo "ERROR: Unable to copy package to final output location"
    echo -e "--------------------------- \n${copied}\n---------------------------------"
    exit 1
  fi
  echo "Package saved to '${destination}'"
}

UpdatePackageFile()
{
  echo "Updating package.json"
  local ERROR=$FALSE

  local package_filename="${output_directory}/package/package.json"
  local package_tmp="${package_filename}.tmp"

  updated=`jq '
    del(.canonical) |
    del(.title) |
    del(.type) |
    del(.url) |
    del(."tools-version") |
    del(."date") |
    del(.license) |
    del(."notForPublication") |
    del(.dependencies."hl7.terminology.r4") |
    del(.dependencies."hl7.fhir.uv.extensions.r4") |
    .name = "iknl.fhir.nl.r4.ncr-ehr" |
    . += {jurisdiction: "urn:iso:std:iso:3166#NL"} |
    .description = "FHIR R4 profiles for the electronic health record (EHR) submissions to the Netherlands Cancer Registry (NCR)" |
    del(."directories") |
    del(."maintainers")
  ' "${package_filename}" > "${package_tmp}" 2>&1` || ERROR=$TRUE

  if [[ ${ERROR} -eq ${TRUE} ]]; then
    echo "ERROR: Unable to update package.json"
    echo -e "--------------------------- \n${updated}\n---------------------------------"
    rm -f "${package_tmp}"
    exit 1
  fi

  moved=`mv "${package_tmp}" "${package_filename}" 2>&1` || ERROR=$TRUE
  if [[ ${ERROR} -eq ${TRUE} ]]; then
    echo "ERROR: Unable to save updated package.json"
    echo -e "--------------------------- \n${moved}\n---------------------------------"
    exit 1
  fi
}

for arg in "$@";
do
  name="${arg/=*/}"
  value="${arg/${name}=/}"
  case "${name}" in
    --package-name)
      [[ "${value}" == "${name}" ]] && echo "No package name provided" && exit 1
      PACKAGE_NAME="${value}"
      ;;
    --filename)
      [[ "${value}" == "${name}" ]] && echo "No filename provided" && exit 1
      OUTPUT_FILENAME="${value}"
      PACKAGE_NAME="${value%.tgz}"
      ;;
 esac
done

[[ "${PACKAGE_NAME}" == "" ]] && echo "No package name was provided, use '--package-name' or '--filename' as an argument to specify a package name" && exit 1
[[ ! -d "${ig_builder_output_path}" ]] && echo "IG output path ${ig_builder_output_path} does not exist" && exit 1
[[ ! $(ls -A ${ig_builder_output_path}) ]] && echo "IG Output directory is empty" && exit 1

PrepareOutputDirectory
UnpackTarFile
RemoveUnwantedFiles
RemoveUnwantedDirs
UpdatePackageFile
CreateTarFile
CopyToFinalOutput

echo "Done."